export declare const DATASOURCE_NAMES: {
    header: string;
    tag: string;
    formDA: string;
    fieldDA: string;
    attachmentACL: string;
    uiAction: string;
    clientScriptEnv: string;
    formLayout: string;
    dataLookup: string;
    currentUser: string;
    fieldValidator: string;
    uiScript: string;
    registeredModal: string;
    activityStream: string;
    ribbon: string;
    shn: string;
    sessionMessage: string;
    simpleFormLayout: string;
};
