"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QUERY_CHANGED = exports.CONTENT_ITEMS_SELECTED = exports.EXTERNAL_ACTIONS = exports.TOGGLE_DOMAIN_SCOPE = exports.OPEN_PHONE = exports.PHONE_ADDON_ACTION_CLICK = exports.REFERENCE_INFO_CLICK = exports.EXECUTE_UI_ACTION = exports.SET_FIELDS_VALUE = exports.FORM_UPDATE_HEADER = exports.PREVIEW_RECORD = exports.REMOVE_NOTIFICATION = exports.CLEAR_NOTIFICATIONS = exports.ADD_NOTIFICATIONS = exports.RECORD_NOTIFICATIONS_CHANGED = exports.WORKSPACE_FORM_ACTION = void 0;
exports.WORKSPACE_FORM_ACTION = 'WORKSPACE_FORM_ACTION';
// Notifications component actions
exports.RECORD_NOTIFICATIONS_CHANGED = 'RECORD_NOTIFICATIONS_CHANGED';
exports.ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS';
exports.CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
exports.REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
// Workspace chrome action
exports.PREVIEW_RECORD = 'PREVIEW_RECORD';
// Form Data action
exports.FORM_UPDATE_HEADER = 'FORM_UPDATE_HEADER';
// Agent Assist actions
exports.SET_FIELDS_VALUE = 'SET_FIELDS_VALUE';
exports.EXECUTE_UI_ACTION = 'EXECUTE_UI_ACTION';
// Reference field action
exports.REFERENCE_INFO_CLICK = 'REFERENCE_INFO_CLICK';
// Phone field action
exports.PHONE_ADDON_ACTION_CLICK = 'PHONE_ADDON_ACTION_CLICK';
// CTI action
exports.OPEN_PHONE = 'OPEN_PHONE';
// Toggle domain scope
exports.TOGGLE_DOMAIN_SCOPE = 'TOGGLE_DOMAIN_SCOPE';
exports.EXTERNAL_ACTIONS = {
    SEND_FORM_NOTIFICATION: 'SEND_FORM_NOTIFICATION'
};
exports.CONTENT_ITEMS_SELECTED = 'CONTENT_ITEMS_SELECTED';
exports.QUERY_CHANGED = 'QUERY_CHANGED';
