export declare const WORKSPACE_FORM_ACTION = "WORKSPACE_FORM_ACTION";
export declare const RECORD_NOTIFICATIONS_CHANGED = "RECORD_NOTIFICATIONS_CHANGED";
export declare const ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS";
export declare const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export declare const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export declare const PREVIEW_RECORD = "PREVIEW_RECORD";
export declare const FORM_UPDATE_HEADER = "FORM_UPDATE_HEADER";
export declare const SET_FIELDS_VALUE = "SET_FIELDS_VALUE";
export declare const EXECUTE_UI_ACTION = "EXECUTE_UI_ACTION";
export declare const REFERENCE_INFO_CLICK = "REFERENCE_INFO_CLICK";
export declare const PHONE_ADDON_ACTION_CLICK = "PHONE_ADDON_ACTION_CLICK";
export declare const OPEN_PHONE = "OPEN_PHONE";
export declare const TOGGLE_DOMAIN_SCOPE = "TOGGLE_DOMAIN_SCOPE";
export declare const EXTERNAL_ACTIONS: {
    SEND_FORM_NOTIFICATION: string;
};
export declare const CONTENT_ITEMS_SELECTED = "CONTENT_ITEMS_SELECTED";
export declare const QUERY_CHANGED = "QUERY_CHANGED";
